package com.physics.tutor.util

import com.physics.tutor.data.db.dao.QuestionDao
import com.physics.tutor.data.db.entity.Question

/**
 * Заполняет базу данных начальным набором вопросов по физике.
 *
 * Вопросы соответствуют ФГОС РФ для классов 7–11.
 * По 12 вопросов на каждый класс, 3 уровня сложности:
 *   difficulty = 1 → Начальный (понятия и определения)
 *   difficulty = 2 → Базовый   (стандартные задачи и формулы)
 *   difficulty = 3 → Продвинутый (расчётные задачи)
 */
object DatabasePopulator {

    suspend fun populate(dao: QuestionDao) {
        if (dao.getCount() > 0) return // Не дублируем при повторном запуске
        dao.insertAll(buildQuestions())
    }

    private fun buildQuestions(): List<Question> = listOf(

        // ══════════════════ 7 КЛАСС ══════════════════
        // Темы: строение вещества, плотность, силы, давление, механическая работа и мощность

        Question(grade = 7, topic = "Строение вещества", difficulty = 1,
            questionText = "Что называется физическим телом?",
            optionA = "Вещество, из которого сделан предмет",
            optionB = "Любой предмет окружающего мира",
            optionC = "Природное явление",
            optionD = "Единица физической величины",
            correctAnswer = "B"),

        Question(grade = 7, topic = "Строение вещества", difficulty = 1,
            questionText = "Чему равна единица измерения длины в системе СИ?",
            optionA = "Миллиметр",
            optionB = "Сантиметр",
            optionC = "Метр",
            optionD = "Километр",
            correctAnswer = "C"),

        Question(grade = 7, topic = "Строение вещества", difficulty = 1,
            questionText = "Что называется плотностью вещества?",
            optionA = "Масса тела",
            optionB = "Объём тела",
            optionC = "Масса единицы объёма вещества",
            optionD = "Сила тяжести, действующая на тело",
            correctAnswer = "C"),

        Question(grade = 7, topic = "Силы", difficulty = 1,
            questionText = "В каких единицах измеряется сила в системе СИ?",
            optionA = "Килограмм",
            optionB = "Ньютон",
            optionC = "Джоуль",
            optionD = "Паскаль",
            correctAnswer = "B"),

        Question(grade = 7, topic = "Силы", difficulty = 2,
            questionText = "Чему равна сила тяжести тела массой 3 кг? (g = 10 м/с²)",
            optionA = "3 Н",
            optionB = "0,3 Н",
            optionC = "30 Н",
            optionD = "300 Н",
            correctAnswer = "C"),

        Question(grade = 7, topic = "Строение вещества", difficulty = 2,
            questionText = "Масса тела 6 кг, объём 0,3 м³. Чему равна плотность вещества?",
            optionA = "0,05 кг/м³",
            optionB = "20 кг/м³",
            optionC = "1,8 кг/м³",
            optionD = "6,3 кг/м³",
            correctAnswer = "B"),

        Question(grade = 7, topic = "Давление", difficulty = 2,
            questionText = "Давление вычисляется по формуле:",
            optionA = "P = m · V",
            optionB = "P = F · S",
            optionC = "P = F / S",
            optionD = "P = m · g",
            correctAnswer = "C"),

        Question(grade = 7, topic = "Механическая работа", difficulty = 2,
            questionText = "Тело движется равномерно прямолинейно. Что это означает?",
            optionA = "Скорость тела увеличивается",
            optionB = "Скорость тела уменьшается",
            optionC = "Скорость тела не изменяется",
            optionD = "Тело находится в покое",
            correctAnswer = "C"),

        Question(grade = 7, topic = "Давление", difficulty = 3,
            questionText = "На горизонтальную поверхность действует сила 120 Н на площадь 0,4 м². Каково давление?",
            optionA = "48 Па",
            optionB = "300 Па",
            optionC = "480 Па",
            optionD = "0,003 Па",
            correctAnswer = "B"),

        Question(grade = 7, topic = "Механическая работа", difficulty = 3,
            questionText = "КПД простого механизма 80%. Полезная работа 400 Дж. Чему равна затраченная работа?",
            optionA = "320 Дж",
            optionB = "500 Дж",
            optionC = "480 Дж",
            optionD = "450 Дж",
            correctAnswer = "B"),

        Question(grade = 7, topic = "Силы", difficulty = 2,
            questionText = "Архимедова сила, действующая на тело в жидкости, зависит от:",
            optionA = "Массы тела",
            optionB = "Плотности жидкости и объёма вытесненной жидкости",
            optionC = "Скорости движения тела",
            optionD = "Температуры жидкости",
            correctAnswer = "B"),

        Question(grade = 7, topic = "Механическая работа", difficulty = 3,
            questionText = "Мощность двигателя 1500 Вт. За сколько секунд он совершит работу 7500 Дж?",
            optionA = "10 с",
            optionB = "5 с",
            optionC = "7500 с",
            optionD = "50 с",
            correctAnswer = "B"),

        // ══════════════════ 8 КЛАСС ══════════════════
        // Темы: тепловые явления, электрический ток, световые явления

        Question(grade = 8, topic = "Тепловые явления", difficulty = 1,
            questionText = "Что называется теплопроводностью?",
            optionA = "Передача тепла через вакуум",
            optionB = "Передача тепла при перемешивании частей жидкости или газа",
            optionC = "Передача тепла от частицы к частице при их взаимодействии",
            optionD = "Нагрев тела солнечными лучами",
            correctAnswer = "C"),

        Question(grade = 8, topic = "Тепловые явления", difficulty = 1,
            questionText = "Единица количества теплоты в системе СИ:",
            optionA = "Ватт",
            optionB = "Ньютон",
            optionC = "Джоуль",
            optionD = "Паскаль",
            correctAnswer = "C"),

        Question(grade = 8, topic = "Тепловые явления", difficulty = 1,
            questionText = "При каком процессе вещество переходит из жидкого состояния в газообразное?",
            optionA = "Конденсация",
            optionB = "Испарение",
            optionC = "Плавление",
            optionD = "Кристаллизация",
            correctAnswer = "B"),

        Question(grade = 8, topic = "Тепловые явления", difficulty = 2,
            questionText = "Удельная теплоёмкость воды 4200 Дж/(кг·°C). Сколько теплоты нужно для нагрева 2 кг воды на 10 °C?",
            optionA = "420 Дж",
            optionB = "840 Дж",
            optionC = "84000 Дж",
            optionD = "21000 Дж",
            correctAnswer = "C"),

        Question(grade = 8, topic = "Электрический ток", difficulty = 1,
            questionText = "Что такое электрический ток?",
            optionA = "Движение электронов в вакууме",
            optionB = "Упорядоченное движение заряженных частиц",
            optionC = "Хаотическое движение молекул",
            optionD = "Перемещение нейтральных атомов",
            correctAnswer = "B"),

        Question(grade = 8, topic = "Электрический ток", difficulty = 2,
            questionText = "Закон Ома для участка цепи: сила тока I равна:",
            optionA = "U · R",
            optionB = "U / R",
            optionC = "R / U",
            optionD = "U + R",
            correctAnswer = "B"),

        Question(grade = 8, topic = "Электрический ток", difficulty = 2,
            questionText = "Сопротивление участка цепи 5 Ом, напряжение 10 В. Чему равна сила тока?",
            optionA = "50 А",
            optionB = "0,5 А",
            optionC = "2 А",
            optionD = "15 А",
            correctAnswer = "C"),

        Question(grade = 8, topic = "Электрический ток", difficulty = 3,
            questionText = "При последовательном соединении R₁ = 4 Ом и R₂ = 6 Ом, напряжение на всём участке 20 В. Чему равна сила тока?",
            optionA = "1 А",
            optionB = "2 А",
            optionC = "5 А",
            optionD = "10 А",
            correctAnswer = "B"),

        Question(grade = 8, topic = "Световые явления", difficulty = 1,
            questionText = "Что называется фокусом собирающей линзы?",
            optionA = "Центр линзы",
            optionB = "Точка, в которой собираются лучи после преломления",
            optionC = "Оптическая ось линзы",
            optionD = "Вершина линзы",
            correctAnswer = "B"),

        Question(grade = 8, topic = "Световые явления", difficulty = 2,
            questionText = "Световой луч переходит из воздуха в стекло. Что происходит с его скоростью?",
            optionA = "Увеличивается",
            optionB = "Не изменяется",
            optionC = "Уменьшается",
            optionD = "Зависит только от цвета луча",
            correctAnswer = "C"),

        Question(grade = 8, topic = "Световые явления", difficulty = 2,
            questionText = "Угол падения луча на плоское зеркало равен 30°. Чему равен угол отражения?",
            optionA = "60°",
            optionB = "30°",
            optionC = "90°",
            optionD = "15°",
            correctAnswer = "B"),

        Question(grade = 8, topic = "Электрический ток", difficulty = 3,
            questionText = "Мощность электроприбора 1000 Вт, напряжение 200 В. Чему равно его сопротивление?",
            optionA = "200 000 Ом",
            optionB = "40 Ом",
            optionC = "5 Ом",
            optionD = "0,005 Ом",
            correctAnswer = "B"),

        // ══════════════════ 9 КЛАСС ══════════════════
        // Темы: законы Ньютона, механические колебания, строение атома

        Question(grade = 9, topic = "Законы Ньютона", difficulty = 1,
            questionText = "Первый закон Ньютона гласит:",
            optionA = "F = m · a",
            optionB = "Тело сохраняет состояние покоя или равномерного прямолинейного движения, если на него не действуют другие тела",
            optionC = "Действие равно противодействию",
            optionD = "Ускорение пропорционально силе и обратно пропорционально массе",
            correctAnswer = "B"),

        Question(grade = 9, topic = "Законы Ньютона", difficulty = 1,
            questionText = "Единица ускорения в системе СИ:",
            optionA = "м/с",
            optionB = "м/с²",
            optionC = "Н",
            optionD = "Дж",
            correctAnswer = "B"),

        Question(grade = 9, topic = "Законы Ньютона", difficulty = 2,
            questionText = "Сила 10 Н действует на тело массой 2 кг. Чему равно ускорение?",
            optionA = "20 м/с²",
            optionB = "5 м/с²",
            optionC = "0,2 м/с²",
            optionD = "12 м/с²",
            correctAnswer = "B"),

        Question(grade = 9, topic = "Законы Ньютона", difficulty = 2,
            questionText = "Импульс тела p вычисляется по формуле:",
            optionA = "p = m · a",
            optionB = "p = m · v",
            optionC = "p = F · t",
            optionD = "p = m · g",
            correctAnswer = "B"),

        Question(grade = 9, topic = "Законы Ньютона", difficulty = 2,
            questionText = "Тело бросают горизонтально. Какое движение оно совершает?",
            optionA = "Только горизонтальное равномерное",
            optionB = "Только вертикальное свободное падение",
            optionC = "Сложное: горизонтальное равномерное и вертикальное равноускоренное",
            optionD = "Равномерное по окружности",
            correctAnswer = "C"),

        Question(grade = 9, topic = "Колебания и волны", difficulty = 1,
            questionText = "Что такое механические колебания?",
            optionA = "Движение тела по окружности",
            optionB = "Повторяющееся движение тела около положения равновесия",
            optionC = "Движение с постоянной скоростью",
            optionD = "Движение только под действием силы тяжести",
            correctAnswer = "B"),

        Question(grade = 9, topic = "Колебания и волны", difficulty = 2,
            questionText = "Период колебаний маятника 2 с. Чему равна частота?",
            optionA = "2 Гц",
            optionB = "0,5 Гц",
            optionC = "4 Гц",
            optionD = "1 Гц",
            correctAnswer = "B"),

        Question(grade = 9, topic = "Строение атома", difficulty = 1,
            questionText = "Из чего состоит атомное ядро?",
            optionA = "Из электронов и протонов",
            optionB = "Из протонов и нейтронов",
            optionC = "Только из нейтронов",
            optionD = "Из молекул вещества",
            correctAnswer = "B"),

        Question(grade = 9, topic = "Строение атома", difficulty = 2,
            questionText = "Какое из радиоактивных излучений не отклоняется магнитным полем?",
            optionA = "α-излучение",
            optionB = "β-излучение",
            optionC = "γ-излучение",
            optionD = "Все три отклоняются",
            correctAnswer = "C"),

        Question(grade = 9, topic = "Строение атома", difficulty = 3,
            questionText = "При α-распаде ядро урана U-238 испускает α-частицу (2 протона, 2 нейтрона). Массовое число продукта равно:",
            optionA = "240",
            optionB = "236",
            optionC = "238",
            optionD = "234",
            correctAnswer = "D"),

        Question(grade = 9, topic = "Колебания и волны", difficulty = 2,
            questionText = "Скорость звука в воздухе при нормальных условиях приблизительно равна:",
            optionA = "300 000 км/с",
            optionB = "340 м/с",
            optionC = "3 км/с",
            optionD = "33 м/с",
            correctAnswer = "B"),

        Question(grade = 9, topic = "Законы Ньютона", difficulty = 3,
            questionText = "Тело движется по окружности радиусом 2 м со скоростью 4 м/с. Центростремительное ускорение равно:",
            optionA = "8 м/с²",
            optionB = "16 м/с²",
            optionC = "2 м/с²",
            optionD = "32 м/с²",
            correctAnswer = "A"),

        Question(grade = 9, topic = "Строение атома", difficulty = 3,
            questionText = "Период полураспада изотопа — 5 лет. Через сколько лет останется 1/4 начального количества вещества?",
            optionA = "5 лет",
            optionB = "10 лет",
            optionC = "15 лет",
            optionD = "20 лет",
            correctAnswer = "B"),

        // ══════════════════ 10 КЛАСС ══════════════════
        // Темы: кинематика, динамика, термодинамика, электростатика

        Question(grade = 10, topic = "Кинематика", difficulty = 1,
            questionText = "Что изучает кинематика?",
            optionA = "Причины движения тел",
            optionB = "Движение тел без учёта причин, его вызывающих",
            optionC = "Взаимодействие тел",
            optionD = "Строение вещества",
            correctAnswer = "B"),

        Question(grade = 10, topic = "Кинематика", difficulty = 2,
            questionText = "При равноускоренном движении v₀ = 0, a = 5 м/с², t = 4 с. Скорость тела в конце движения:",
            optionA = "9 м/с",
            optionB = "20 м/с",
            optionC = "1,25 м/с",
            optionD = "0,8 м/с",
            correctAnswer = "B"),

        Question(grade = 10, topic = "Динамика", difficulty = 2,
            questionText = "Закон всемирного тяготения: сила притяжения между телами...",
            optionA = "Пропорциональна массам и квадрату расстояния между ними",
            optionB = "Пропорциональна произведению масс и обратно пропорциональна квадрату расстояния",
            optionC = "Не зависит от расстояния между телами",
            optionD = "Пропорциональна только произведению масс",
            correctAnswer = "B"),

        Question(grade = 10, topic = "Динамика", difficulty = 2,
            questionText = "Работа A = F · s · cosα. При угле α = 90° работа равна:",
            optionA = "F · s",
            optionB = "0",
            optionC = "−F · s",
            optionD = "F · s / 2",
            correctAnswer = "B"),

        Question(grade = 10, topic = "Термодинамика", difficulty = 1,
            questionText = "Что такое внутренняя энергия тела?",
            optionA = "Кинетическая энергия тела как целого",
            optionB = "Потенциальная энергия тела в поле тяжести",
            optionC = "Сумма кинетических и потенциальных энергий всех молекул тела",
            optionD = "Работа сил давления",
            correctAnswer = "C"),

        Question(grade = 10, topic = "Термодинамика", difficulty = 1,
            questionText = "Первое начало термодинамики: изменение внутренней энергии тела ΔU равно:",
            optionA = "Совершённой телом работе A",
            optionB = "Количеству теплоты Q",
            optionC = "Q − A",
            optionD = "Q + A",
            correctAnswer = "C"),

        Question(grade = 10, topic = "Термодинамика", difficulty = 2,
            questionText = "Идеальный газ нагревают при постоянном объёме (изохорный процесс). Что изменяется?",
            optionA = "Объём",
            optionB = "Давление",
            optionC = "Масса газа",
            optionD = "Плотность газа",
            correctAnswer = "B"),

        Question(grade = 10, topic = "Термодинамика", difficulty = 3,
            questionText = "КПД тепловой машины η = 1 − T₂/T₁. При T₁ = 600 К и T₂ = 400 К КПД равен:",
            optionA = "0,33",
            optionB = "0,67",
            optionC = "0,50",
            optionD = "0,25",
            correctAnswer = "A"),

        Question(grade = 10, topic = "Электростатика", difficulty = 2,
            questionText = "Напряжённость электрического поля E вычисляется по формуле:",
            optionA = "E = F · q",
            optionB = "E = F / q",
            optionC = "E = q / F",
            optionD = "E = F · q²",
            correctAnswer = "B"),

        Question(grade = 10, topic = "Кинематика", difficulty = 3,
            questionText = "Тело движется по закону x = 5 + 3t + 2t² (м). Ускорение тела равно:",
            optionA = "3 м/с²",
            optionB = "4 м/с²",
            optionC = "2 м/с²",
            optionD = "5 м/с²",
            correctAnswer = "B"),

        Question(grade = 10, topic = "Электростатика", difficulty = 3,
            questionText = "Два заряда q₁ = 2 нКл и q₂ = 3 нКл на расстоянии r = 3 см. Сила взаимодействия (k = 9·10⁹ Н·м²/Кл²):",
            optionA = "60 мкН",
            optionB = "6 нН",
            optionC = "60 мН",
            optionD = "0,06 мкН",
            correctAnswer = "A"),

        Question(grade = 10, topic = "Электростатика", difficulty = 3,
            questionText = "Конденсатор ёмкостью 2 мкФ заряжен до напряжения 100 В. Заряд конденсатора равен:",
            optionA = "200 мкКл",
            optionB = "50 мкКл",
            optionC = "0,02 мкКл",
            optionD = "200 Кл",
            correctAnswer = "A"),

        Question(grade = 10, topic = "Динамика", difficulty = 3,
            questionText = "Тело массой 5 кг брошено вертикально вверх со скоростью 20 м/с. На какую максимальную высоту оно поднимется? (g = 10 м/с²)",
            optionA = "10 м",
            optionB = "20 м",
            optionC = "40 м",
            optionD = "2 м",
            correctAnswer = "B"),

        // ══════════════════ 11 КЛАСС ══════════════════
        // Темы: электромагнитная индукция, оптика, квантовая физика

        Question(grade = 11, topic = "Электромагнитная индукция", difficulty = 1,
            questionText = "Что такое электромагнитная индукция?",
            optionA = "Возникновение ЭДС в проводнике, находящемся в переменном магнитном поле",
            optionB = "Намагничивание железа",
            optionC = "Действие тока на постоянный магнит",
            optionD = "Нагрев проводника при прохождении через него тока",
            correctAnswer = "A"),

        Question(grade = 11, topic = "Оптика", difficulty = 1,
            questionText = "Длина волны видимого света находится примерно в диапазоне:",
            optionA = "0,4–0,7 мм",
            optionB = "400–700 нм",
            optionC = "4–7 мкм",
            optionD = "0,004–0,007 нм",
            correctAnswer = "B"),

        Question(grade = 11, topic = "Электромагнитная индукция", difficulty = 2,
            questionText = "ЭДС индукции: ε = −ΔΦ/Δt. Поток изменился на 10 Вб за 2 с. Модуль ЭДС равен:",
            optionA = "20 В",
            optionB = "0,2 В",
            optionC = "5 В",
            optionD = "12 В",
            correctAnswer = "C"),

        Question(grade = 11, topic = "Электромагнитная индукция", difficulty = 2,
            questionText = "Трансформатор является повышающим, если:",
            optionA = "Число витков во вторичной обмотке больше, чем в первичной",
            optionB = "Число витков в первичной обмотке больше",
            optionC = "Обмотки содержат одинаковое число витков",
            optionD = "Сердечник изготовлен из меди",
            correctAnswer = "A"),

        Question(grade = 11, topic = "Квантовая физика", difficulty = 1,
            questionText = "Явление фотоэффекта объясняет:",
            optionA = "Волновая теория света",
            optionB = "Квантовая (корпускулярная) теория света",
            optionC = "Специальная теория относительности",
            optionD = "Молекулярно-кинетическая теория",
            correctAnswer = "B"),

        Question(grade = 11, topic = "Квантовая физика", difficulty = 1,
            questionText = "Какая из перечисленных частиц не имеет электрического заряда?",
            optionA = "Электрон",
            optionB = "Протон",
            optionC = "Нейтрон",
            optionD = "Позитрон",
            correctAnswer = "C"),

        Question(grade = 11, topic = "Оптика", difficulty = 2,
            questionText = "Магнитный поток Φ вычисляется по формуле:",
            optionA = "Φ = B · I · l",
            optionB = "Φ = B · S · cosα",
            optionC = "Φ = B · S · sinα",
            optionD = "Φ = I · l · B",
            correctAnswer = "B"),

        Question(grade = 11, topic = "Оптика", difficulty = 2,
            questionText = "Луч переходит из стекла (n = 1,5) в воздух (n = 1). Угол падения 30°. Угол преломления равен приблизительно:",
            optionA = "30°",
            optionB = "20°",
            optionC = "48,6°",
            optionD = "90°",
            correctAnswer = "C"),

        Question(grade = 11, topic = "Квантовая физика", difficulty = 3,
            questionText = "Фотон с длиной волны λ = 500 нм имеет энергию (h = 6,63·10⁻³⁴ Дж·с, c = 3·10⁸ м/с):",
            optionA = "≈ 4·10⁻¹⁹ Дж",
            optionB = "≈ 4·10⁻²⁸ Дж",
            optionC = "≈ 4·10⁻¹² Дж",
            optionD = "≈ 1·10⁻²⁰ Дж",
            correctAnswer = "A"),

        Question(grade = 11, topic = "Квантовая физика", difficulty = 3,
            questionText = "Период полураспада изотопа 8 лет. Через сколько лет останется 1/8 начального количества атомов?",
            optionA = "8 лет",
            optionB = "16 лет",
            optionC = "24 лет",
            optionD = "32 лет",
            correctAnswer = "C"),

        Question(grade = 11, topic = "Электромагнитная индукция", difficulty = 3,
            questionText = "Контур LC-генератора: L = 0,1 Гн, C = 100 мкФ. Период колебаний T = 2π√(LC) равен приблизительно:",
            optionA = "0,02 с",
            optionB = "0,063 с",
            optionC = "0,628 с",
            optionD = "0,1 с",
            correctAnswer = "A"),

        Question(grade = 11, topic = "Квантовая физика", difficulty = 3,
            questionText = "Работа выхода электрона из металла 2 эВ. Максимальная кинетическая энергия фотоэлектронов при частоте света ν = 7·10¹⁴ Гц (h = 6,63·10⁻³⁴ Дж·с) равна приблизительно:",
            optionA = "0,64 эВ",
            optionB = "2,64 эВ",
            optionC = "0,9 эВ",
            optionD = "1,6 эВ",
            correctAnswer = "C"),

        Question(grade = 11, topic = "Оптика", difficulty = 3,
            questionText = "Линза с фокусным расстоянием F = 20 см. Предмет расположен на расстоянии d = 30 см от линзы. Расстояние до изображения v определяется по формуле 1/v = 1/F − 1/d. v равно:",
            optionA = "12 см",
            optionB = "60 см",
            optionC = "10 см",
            optionD = "50 см",
            correctAnswer = "B")
    )
}
